require("dotenv").config()
const mongoose = require("mongoose")
const connectDB = require("./config/db.js")
const Trip = require("./models/Trip.js")
const User = require("./models/User.js")
const Restaurant = require('./models/Restaurant');

const tripsData = [
  // === TOP DESTINATIONS (High Rating & Popular) ===
  {
    title: "Bali Ultimate Paradise",
    location: "Indonesia",
    destination: "Bali",
    duration: "7 Days",
    price: 1299,
    originalPrice: 1599,
    discount: 19,
    rating: 4.9,
    image: "🏝️",
    gradient: ["#FF6B6B", "#4ECDC4"],
    tag: "🔥 HOT DEAL",
    highlights: ["Beach Resort", "Temple Tours", "Spa Treatment", "Sunset Views"],
    category: "Relaxation",
    subCategories: ["Beach", "Wellness"],
    difficulty: "Easy",
    status: "popular",
    type: "Package",
    provider: "TravelMate Premium",
    time: "Year-round",
    passengers: 2,
    guests: 2,
  },
  {
    title: "Swiss Alps Adventure",
    location: "Switzerland",
    destination: "Zermatt",
    duration: "5 Days",
    price: 2199,
    originalPrice: 2599,
    discount: 15,
    rating: 4.8,
    image: "⛰️",
    gradient: ["#667eea", "#764ba2"],
    tag: "⭐ PREMIUM",
    highlights: ["Cable Car", "Hiking", "Local Cuisine", "Mountain Views"],
    category: "Adventure",
    subCategories: ["Mountain", "Sports"],
    difficulty: "Moderate",
    status: "popular",
    type: "Package",
    provider: "Alpine Adventures",
    time: "Summer",
    passengers: 4,
    guests: 4,
  },
  {
    title: "Tokyo Cultural Explorer",
    location: "Japan",
    destination: "Tokyo",
    duration: "6 Days",
    price: 1899,
    originalPrice: 2199,
    discount: 14,
    rating: 4.7,
    image: "🏯",
    gradient: ["#f093fb", "#f5576c"],
    tag: "🎌 CULTURAL",
    highlights: ["City Tours", "Food Tours", "Traditional Shows", "Temples"],
    category: "Cultural",
    subCategories: ["City", "Heritage", "Food"],
    difficulty: "Easy",
    status: "popular",
    type: "Package",
    provider: "Japan Tours",
    time: "Spring/Fall",
    passengers: 2,
    guests: 2,
  },
  {
    title: "Safari Serengeti",
    location: "Tanzania",
    destination: "Serengeti",
    duration: "8 Days",
    price: 2799,
    originalPrice: 3299,
    discount: 15,
    rating: 4.9,
    image: "🦁",
    gradient: ["#4ECDC4", "#44A08D"],
    tag: "🦁 WILDLIFE",
    highlights: ["Game Drives", "Luxury Lodge", "Photography", "Sunrise Safari"],
    category: "Adventure",
    subCategories: ["Wildlife", "Nature"],
    difficulty: "Easy",
    status: "popular",
    type: "Package",
    provider: "Wildlife Expeditions",
    time: "Migration Season",
    passengers: 6,
    guests: 6,
  },

  // === TRENDING NOW ===
  {
    title: "Northern Lights Aurora",
    location: "Norway",
    destination: "Tromsø",
    duration: "4 Days",
    price: 1499,
    rating: 4.8,
    image: "🌌",
    gradient: ["#667eea", "#764ba2"],
    tag: "🔥 TRENDING",
    highlights: ["Aurora Viewing", "Dog Sledding", "Ice Hotel"],
    category: "Adventure",
    subCategories: ["Nature", "Photography"],
    difficulty: "Moderate",
    status: "trending",
    type: "Experience",
    provider: "Arctic Adventures",
    time: "Winter",
    passengers: 2,
    guests: 2,
  },
  {
    title: "Desert Safari Dubai",
    location: "UAE",
    destination: "Dubai",
    duration: "3 Days",
    price: 899,
    rating: 4.7,
    image: "🏜️",
    gradient: ["#FF6B6B", "#4ECDC4"],
    tag: "🔥 TRENDING",
    highlights: ["Desert Safari", "Camel Ride", "Sunset Views"],
    category: "Adventure",
    subCategories: ["Nature", "Photography"],
    difficulty: "Easy",
    status: "trending",
    type: "Experience",
    provider: "Desert Tours",
    time: "Year-round",
    passengers: 4,
    guests: 4,
  },
  {
    title: "Cherry Blossom Japan",
    location: "Japan",
    destination: "Kyoto",
    duration: "5 Days",
    price: 1299,
    rating: 4.9,
    image: "🌸",
    gradient: ["#f093fb", "#f5576c"],
    tag: "🌸 SEASONAL",
    highlights: ["Cherry Blossoms", "Temple Tours", "Traditional Gardens"],
    category: "Cultural",
    subCategories: ["Heritage", "Nature"],
    difficulty: "Easy",
    status: "trending",
    type: "Package",
    provider: "Japan Seasons",
    time: "Spring",
    passengers: 2,
    guests: 2,
  },

  // === WEEKEND ESCAPES ===
  {
    title: "Lonavala Hills Retreat",
    location: "India",
    destination: "Lonavala",
    duration: "2 Days",
    price: 299,
    rating: 4.5,
    image: "🏔️",
    gradient: ["#4ECDC4", "#44A08D"],
    highlights: ["Hill Station", "Waterfalls", "Local Food"],
    category: "Relaxation",
    subCategories: ["Mountain", "Nature"],
    difficulty: "Easy",
    status: "weekend",
    type: "Quick Trip",
    provider: "Weekend Getaways",
    time: "Weekend",
    passengers: 2,
    guests: 2,
  },
  {
    title: "Goa Beach Bliss",
    location: "India",
    destination: "Goa",
    duration: "3 Days",
    price: 499,
    rating: 4.6,
    image: "🏖️",
    gradient: ["#FF6B6B", "#4ECDC4"],
    highlights: ["Beach Relaxation", "Water Sports", "Nightlife"],
    category: "Relaxation",
    subCategories: ["Beach", "Nightlife"],
    difficulty: "Easy",
    status: "weekend",
    type: "Quick Trip",
    provider: "Beach Holidays",
    time: "Weekend",
    passengers: 2,
    guests: 2,
  },
  {
    title: "Coorg Coffee Plantations",
    location: "India",
    destination: "Coorg",
    duration: "2 Days",
    price: 399,
    rating: 4.4,
    image: "☕",
    gradient: ["#4ECDC4", "#44A08D"],
    highlights: ["Coffee Estates", "Spice Gardens", "Mountain Views"],
    category: "Cultural",
    subCategories: ["Nature", "Education"],
    difficulty: "Easy",
    status: "weekend",
    type: "Quick Trip",
    provider: "Plantation Tours",
    time: "Weekend",
    passengers: 2,
    guests: 2,
  },

  // === BUDGET FRIENDLY ===
  {
    title: "Vietnam Backpacking",
    location: "Vietnam",
    destination: "Hanoi to Ho Chi Minh",
    duration: "7 Days",
    price: 399,
    rating: 4.6,
    image: "🛵",
    gradient: ["#FF6B6B", "#4ECDC4"],
    highlights: ["Street Food", "Mekong Delta", "Halong Bay"],
    category: "Budget",
    subCategories: ["Food", "City"],
    difficulty: "Moderate",
    status: "budget",
    type: "Backpacking",
    provider: "Budget Travel",
    time: "Year-round",
    passengers: 1,
    guests: 1,
  },
  {
    title: "Hampi Heritage Walk",
    location: "India",
    destination: "Hampi",
    duration: "3 Days",
    price: 199,
    rating: 4.5,
    image: "🏛️",
    gradient: ["#f093fb", "#f5576c"],
    highlights: ["Ancient Ruins", "Temple Architecture", "Sunrise Views"],
    category: "Cultural",
    subCategories: ["Heritage", "Photography"],
    difficulty: "Easy",
    status: "budget",
    type: "Heritage Tour",
    provider: "Heritage Walks",
    time: "Year-round",
    passengers: 2,
    guests: 2,
  },
  {
    title: "Pokhara Lakeside",
    location: "Nepal",
    destination: "Pokhara",
    duration: "4 Days",
    price: 299,
    rating: 4.7,
    image: "🏔️",
    gradient: ["#667eea", "#764ba2"],
    highlights: ["Lake Views", "Mountain Views", "Peace Pagoda"],
    category: "Relaxation",
    subCategories: ["Nature", "Mountain"],
    difficulty: "Easy",
    status: "budget",
    type: "Nature Tour",
    provider: "Nepal Adventures",
    time: "Year-round",
    passengers: 2,
    guests: 2,
  },

  // === FEATURED EXPERIENCES ===
  {
    title: "Amazon Rainforest Expedition",
    location: "Brazil",
    destination: "Manaus",
    duration: "10 Days",
    price: 3499,
    rating: 4.9,
    image: "🌿",
    gradient: ["#4ECDC4", "#44A08D"],
    tag: "⭐ FEATURED",
    highlights: ["Wildlife Spotting", "River Cruises", "Indigenous Culture"],
    category: "Adventure",
    subCategories: ["Wildlife", "Nature"],
    difficulty: "Challenging",
    status: "featured",
    type: "Expedition",
    provider: "Wildlife Expeditions",
    time: "Dry Season",
    passengers: 8,
    guests: 8,
  },
  {
    title: "Great Barrier Reef Diving",
    location: "Australia",
    destination: "Cairns",
    duration: "6 Days",
    price: 2499,
    rating: 4.8,
    image: "🐠",
    gradient: ["#FF6B6B", "#4ECDC4"],
    tag: "⭐ FEATURED",
    highlights: ["Scuba Diving", "Coral Reefs", "Marine Life"],
    category: "Adventure",
    subCategories: ["Sports", "Nature"],
    difficulty: "Moderate",
    status: "featured",
    type: "Diving Tour",
    provider: "Marine Adventures",
    time: "Year-round",
    passengers: 4,
    guests: 4,
  },
  {
    title: "Safari Serengeti Premium",
    location: "Tanzania",
    destination: "Serengeti",
    duration: "8 Days",
    price: 3999,
    rating: 4.9,
    image: "🦓",
    gradient: ["#4ECDC4", "#44A08D"],
    tag: "⭐ PREMIUM",
    highlights: ["Luxury Lodge", "Private Game Drives", "Photography"],
    category: "Luxury",
    subCategories: ["Wildlife", "Nature"],
    difficulty: "Easy",
    status: "featured",
    type: "Luxury Safari",
    provider: "Premium Safaris",
    time: "Migration Season",
    passengers: 4,
    guests: 4,
  },

  // === OFFBEAT ESCAPES ===
  {
    title: "Faroe Islands Adventure",
    location: "Denmark",
    destination: "Faroe Islands",
    duration: "5 Days",
    price: 1899,
    rating: 4.7,
    image: "🏔️",
    gradient: ["#667eea", "#764ba2"],
    tag: "🌿 OFFBEAT",
    highlights: ["Dramatic Landscapes", "Puffin Watching", "Hiking"],
    category: "Adventure",
    subCategories: ["Nature", "Wildlife"],
    difficulty: "Moderate",
    status: "offbeat",
    type: "Nature Tour",
    provider: "Nordic Adventures",
    time: "Summer",
    passengers: 2,
    guests: 2,
  },
  {
    title: "Svalbard Arctic Expedition",
    location: "Norway",
    destination: "Svalbard",
    duration: "7 Days",
    price: 2999,
    rating: 4.8,
    image: "❄️",
    gradient: ["#4ECDC4", "#44A08D"],
    tag: "🌿 UNIQUE",
    highlights: ["Polar Bears", "Northern Lights", "Ice Caves"],
    category: "Adventure",
    subCategories: ["Wildlife", "Nature"],
    difficulty: "Expert",
    status: "offbeat",
    type: "Arctic Expedition",
    provider: "Polar Adventures",
    time: "Winter",
    passengers: 6,
    guests: 6,
  },
  {
    title: "Socotra Island Discovery",
    location: "Yemen",
    destination: "Socotra",
    duration: "6 Days",
    price: 1599,
    rating: 4.6,
    image: "🌵",
    gradient: ["#FF6B6B", "#4ECDC4"],
    tag: "🌿 HIDDEN GEM",
    highlights: ["Dragon Blood Trees", "Desert Landscapes", "Beaches"],
    category: "Adventure",
    subCategories: ["Nature", "Beach"],
    difficulty: "Moderate",
    status: "offbeat",
    type: "Discovery Tour",
    provider: "Desert Expeditions",
    time: "Spring/Fall",
    passengers: 4,
    guests: 4,
  },

  // === PARTY ESCAPES ===
  {
    title: "Ibiza Nightlife Experience",
    location: "Spain",
    destination: "Ibiza",
    duration: "5 Days",
    price: 1299,
    rating: 4.7,
    image: "🎉",
    gradient: ["#FF6B6B", "#4ECDC4"],
    tag: "🎉 PARTY",
    highlights: ["Beach Clubs", "Sunset Parties", "Boat Parties"],
    category: "Group",
    subCategories: ["Nightlife", "Beach"],
    difficulty: "Easy",
    status: "party",
    type: "Party Tour",
    provider: "Party Tours",
    time: "Summer",
    passengers: 4,
    guests: 4,
  },
  {
    title: "Full Moon Party Thailand",
    location: "Thailand",
    destination: "Koh Phangan",
    duration: "4 Days",
    price: 599,
    rating: 4.5,
    image: "🌕",
    gradient: ["#f093fb", "#f5576c"],
    tag: "🎉 NIGHTLIFE",
    highlights: ["Beach Parties", "Fire Shows", "Island Hopping"],
    category: "Group",
    subCategories: ["Nightlife", "Beach"],
    difficulty: "Easy",
    status: "party",
    type: "Party Tour",
    provider: "Island Parties",
    time: "Full Moon",
    passengers: 6,
    guests: 6,
  },
  {
    title: "Berlin Techno Scene",
    location: "Germany",
    destination: "Berlin",
    duration: "4 Days",
    price: 899,
    rating: 4.6,
    image: "🎵",
    gradient: ["#667eea", "#764ba2"],
    tag: "🎉 TECHNO",
    highlights: ["Underground Clubs", "Street Art", "Alternative Culture"],
    category: "Group",
    subCategories: ["Nightlife", "City"],
    difficulty: "Easy",
    status: "party",
    type: "City Tour",
    provider: "Urban Adventures",
    time: "Year-round",
    passengers: 4,
    guests: 4,
  },

  // === POPULAR QUICK TRIPS ===
  {
    title: "Sedona Red Rocks",
    location: "USA",
    destination: "Sedona",
    duration: "2 Days",
    price: 399,
    rating: 4.7,
    image: "🏜️",
    gradient: ["#FF6B6B", "#4ECDC4"],
    highlights: ["Red Rock Hiking", "Vortex Sites", "Sunset Views"],
    category: "Adventure",
    subCategories: ["Mountain", "Nature"],
    difficulty: "Easy",
    status: "quick",
    type: "Quick Trip",
    provider: "Desert Adventures",
    time: "Year-round",
    passengers: 2,
    guests: 2,
  },
  {
    title: "Blue Mountains Escape",
    location: "Australia",
    destination: "Blue Mountains",
    duration: "2 Days",
    price: 299,
    rating: 4.6,
    image: "🏔️",
    gradient: ["#4ECDC4", "#44A08D"],
    highlights: ["Scenic Railway", "Waterfalls", "Bushwalking"],
    category: "Relaxation",
    subCategories: ["Mountain", "Nature"],
    difficulty: "Easy",
    status: "quick",
    type: "Quick Trip",
    provider: "Mountain Retreats",
    time: "Year-round",
    passengers: 2,
    guests: 2,
  },
  {
    title: "Lake Bled Paradise",
    location: "Slovenia",
    destination: "Lake Bled",
    duration: "3 Days",
    price: 499,
    rating: 4.8,
    image: "🏞️",
    gradient: ["#667eea", "#764ba2"],
    highlights: ["Lake Views", "Island Church", "Castle Visit"],
    category: "Relaxation",
    subCategories: ["Nature", "Heritage"],
    difficulty: "Easy",
    status: "quick",
    type: "Quick Trip",
    provider: "Alpine Retreats",
    time: "Summer",
    passengers: 2,
    guests: 2,
  },
  {
    title: "Hallstatt Village",
    location: "Austria",
    destination: "Hallstatt",
    duration: "2 Days",
    price: 399,
    rating: 4.7,
    image: "🏘️",
    gradient: ["#f093fb", "#f5576c"],
    highlights: ["Alpine Village", "Salt Mines", "Lake Views"],
    category: "Cultural",
    subCategories: ["Heritage", "Nature"],
    difficulty: "Easy",
    status: "quick",
    type: "Quick Trip",
    provider: "Village Tours",
    time: "Year-round",
    passengers: 2,
    guests: 2,
  },

  // === HONEYMOON SPECIALS ===
  {
    title: "Maldives Overwater Villa",
    location: "Maldives",
    destination: "Male Atoll",
    duration: "7 Days",
    price: 4999,
    rating: 4.9,
    image: "🏖️",
    gradient: ["#FF6B6B", "#4ECDC4"],
    tag: "💕 HONEYMOON",
    highlights: ["Overwater Villa", "Private Beach", "Spa Treatment"],
    category: "Honeymoon",
    subCategories: ["Beach", "Wellness"],
    difficulty: "Easy",
    status: "luxury",
    type: "Luxury Package",
    provider: "Luxury Resorts",
    time: "Year-round",
    passengers: 2,
    guests: 2,
  },
  {
    title: "Santorini Sunset Romance",
    location: "Greece",
    destination: "Santorini",
    duration: "6 Days",
    price: 2499,
    rating: 4.8,
    image: "🌅",
    gradient: ["#f093fb", "#f5576c"],
    tag: "💕 ROMANTIC",
    highlights: ["Sunset Views", "Wine Tasting", "Private Tours"],
    category: "Honeymoon",
    subCategories: ["Beach", "Food"],
    difficulty: "Easy",
    status: "luxury",
    type: "Romantic Package",
    provider: "Greek Romance",
    time: "Summer",
    passengers: 2,
    guests: 2,
  },

  // === FAMILY TRIPS ===
  {
    title: "Disney World Magic",
    location: "USA",
    destination: "Orlando",
    duration: "5 Days",
    price: 1899,
    rating: 4.7,
    image: "🏰",
    gradient: ["#FF6B6B", "#4ECDC4"],
    tag: "👨‍👩‍👧‍👦 FAMILY",
    highlights: ["Theme Parks", "Character Meet", "Water Parks"],
    category: "Family",
    subCategories: ["Education", "City"],
    difficulty: "Easy",
    status: "family",
    type: "Family Package",
    provider: "Disney Tours",
    time: "Year-round",
    passengers: 4,
    guests: 4,
  },
  {
    title: "Swiss Family Adventure",
    location: "Switzerland",
    destination: "Interlaken",
    duration: "6 Days",
    price: 2199,
    rating: 4.8,
    image: "🏔️",
    gradient: ["#667eea", "#764ba2"],
    tag: "👨‍👩‍👧‍👦 FAMILY",
    highlights: ["Cable Cars", "Hiking Trails", "Lake Activities"],
    category: "Family",
    subCategories: ["Mountain", "Sports"],
    difficulty: "Moderate",
    status: "family",
    type: "Family Package",
    provider: "Alpine Family Tours",
    time: "Summer",
    passengers: 4,
    guests: 4,
  },

  // === SOLO TRAVEL ===
  {
    title: "Solo Backpacking Europe",
    location: "Europe",
    destination: "Multiple Cities",
    duration: "14 Days",
    price: 1299,
    rating: 4.6,
    image: "🎒",
    gradient: ["#4ECDC4", "#44A08D"],
    tag: "🧳 SOLO",
    highlights: ["Hostel Stays", "City Tours", "Group Activities"],
    category: "Solo",
    subCategories: ["City", "Education"],
    difficulty: "Moderate",
    status: "solo",
    type: "Backpacking",
    provider: "Solo Adventures",
    time: "Summer",
    passengers: 1,
    guests: 1,
  },
  {
    title: "Solo Yoga Retreat Bali",
    location: "Indonesia",
    destination: "Ubud",
    duration: "7 Days",
    price: 899,
    rating: 4.7,
    image: "🧘",
    gradient: ["#f093fb", "#f5576c"],
    tag: "🧳 SOLO",
    highlights: ["Yoga Classes", "Meditation", "Healthy Food"],
    category: "Solo",
    subCategories: ["Wellness", "Education"],
    difficulty: "Easy",
    status: "solo",
    type: "Wellness Retreat",
    provider: "Bali Wellness",
    time: "Year-round",
    passengers: 1,
    guests: 1,
  },

  // === BUSINESS TRAVEL ===
  {
    title: "Singapore Business Hub",
    location: "Singapore",
    destination: "Singapore",
    duration: "4 Days",
    price: 1499,
    rating: 4.6,
    image: "🏢",
    gradient: ["#667eea", "#764ba2"],
    tag: "💼 BUSINESS",
    highlights: ["Business District", "Networking Events", "Fine Dining"],
    category: "Business",
    subCategories: ["City", "Food"],
    difficulty: "Easy",
    status: "business",
    type: "Business Package",
    provider: "Corporate Travel",
    time: "Year-round",
    passengers: 1,
    guests: 1,
  },
  {
    title: "Dubai Conference Center",
    location: "UAE",
    destination: "Dubai",
    duration: "5 Days",
    price: 1799,
    rating: 4.7,
    image: "🏗️",
    gradient: ["#FF6B6B", "#4ECDC4"],
    tag: "💼 BUSINESS",
    highlights: ["Conference Facilities", "Luxury Hotels", "Shopping"],
    category: "Business",
    subCategories: ["City", "Shopping"],
    difficulty: "Easy",
    status: "business",
    type: "Business Package",
    provider: "Corporate Events",
    time: "Year-round",
    passengers: 1,
    guests: 1,
  },

  // === LUXURY EXPERIENCES ===
  {
    title: "Private Jet World Tour",
    location: "Multiple",
    destination: "Global",
    duration: "21 Days",
    price: 49999,
    rating: 4.9,
    image: "✈️",
    gradient: ["#FF6B6B", "#4ECDC4"],
    tag: "💎 LUXURY",
    highlights: ["Private Jet", "Luxury Hotels", "Personal Concierge"],
    category: "Luxury",
    subCategories: ["City", "Education"],
    difficulty: "Easy",
    status: "luxury",
    type: "Luxury Package",
    provider: "Luxury Travel",
    time: "Year-round",
    passengers: 2,
    guests: 2,
  },
  {
    title: "Private Island Retreat",
    location: "Fiji",
    destination: "Private Island",
    duration: "7 Days",
    price: 9999,
    rating: 4.9,
    image: "🏝️",
    gradient: ["#4ECDC4", "#44A08D"],
    tag: "💎 LUXURY",
    highlights: ["Private Island", "Personal Chef", "Water Activities"],
    category: "Luxury",
    subCategories: ["Beach", "Wellness"],
    difficulty: "Easy",
    status: "luxury",
    type: "Luxury Package",
    provider: "Private Islands",
    time: "Year-round",
    passengers: 4,
    guests: 4,
  },
]

const sampleRestaurants = [
  {
    name: 'Goa Beach Shack',
    location: 'Goa',
    cuisines: ['Seafood', 'Goan'],
    menu: [
      { name: 'Fish Curry Rice', price: 350 },
      { name: 'Prawn Masala', price: 400 },
      { name: 'Kingfisher Beer', price: 180 },
    ],
    images: [
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
      'https://images.unsplash.com/photo-1464306076886-debca5e8a6b0',
    ],
    ratings: [],
    description: 'A classic beach shack with fresh seafood and a sea view.',
    openingHours: '10:00 AM - 11:00 PM',
    averageCost: 800,
    contactInfo: {
      phone: '0832-1234567',
      email: 'info@goabeachshack.com',
      address: 'Calangute Beach, Goa',
    },
  },
  {
    name: 'Mumbai Spice',
    location: 'Mumbai',
    cuisines: ['Indian', 'Street Food'],
    menu: [
      { name: 'Vada Pav', price: 50 },
      { name: 'Pav Bhaji', price: 120 },
      { name: 'Masala Chai', price: 30 },
    ],
    images: [
      'https://images.unsplash.com/photo-1516685018646-5499d0a7d42f',
      'https://images.unsplash.com/photo-1502741338009-cac2772e18bc',
    ],
    ratings: [],
    description: 'Authentic Mumbai street food in a modern setting.',
    openingHours: '8:00 AM - 10:00 PM',
    averageCost: 300,
    contactInfo: {
      phone: '022-9876543',
      email: 'contact@mumbaispice.com',
      address: 'Bandra, Mumbai',
    },
  },
  {
    name: 'Delhi Darbar',
    location: 'Delhi',
    cuisines: ['North Indian', 'Mughlai'],
    menu: [
      { name: 'Butter Chicken', price: 350 },
      { name: 'Naan', price: 40 },
      { name: 'Paneer Tikka', price: 220 },
    ],
    images: [
      'https://images.unsplash.com/photo-1523987355523-c7b5b0723c6a',
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    ],
    ratings: [],
    description: 'Famous for its Mughlai cuisine and royal ambiance.',
    openingHours: '11:00 AM - 11:00 PM',
    averageCost: 1000,
    contactInfo: {
      phone: '011-24681012',
      email: 'info@delhidarbar.com',
      address: 'Connaught Place, Delhi',
    },
  },
];

async function seedAll() {
  await connectDB();
  try {
    // Seed Restaurants
    await Restaurant.deleteMany({});
    await Restaurant.insertMany(sampleRestaurants);
    console.log('Sample restaurants seeded!');

    // Seed Trips
    await Trip.deleteMany({});
    await Trip.insertMany(tripsData);
    console.log(`Inserted ${tripsData.length} trips with categories and subcategories`);

    // (Optional) Seed Users, etc.
    // await User.deleteMany({});
    // await User.insertMany(sampleUsers);

    console.log("Database seeded successfully!");
    process.exit(0);
  } catch (err) {
    console.error('Seeding error:', err);
    process.exit(1);
  }
}

seedAll();
